#!/usr/bin/env bash

################################################################
#   Title: Scannergram Bot                                     #
#   Author: Panda Foss                                         #
#   Website: https://pandafoss.github.io/                      #
#   Github: https://github.com/PandaFoss/                      #
#   License: GPLv3 and later                                   #
################################################################

#===  CHECKING TOKENS FILE  ====================================

[[ -f ./tokens ]] && . ./tokens

#== Constants ==================================================

readonly BOT_TOKEN
readonly LOGFILE="./history.log"
readonly TIMEOUT="10"
readonly URL="https://api.telegram.org/bot${BOT_TOKEN}"
readonly FILE_URL="https://api.telegram.org/file/bot${BOT_TOKEN}"
readonly BOTNAME="$(curl --silent "${URL}/getMe"               \
                    | jq .result.username                      \
                    | tr -d '"')"

#== Functions ==================================================

################################################################
#   Description: Sending request to telegram api
#   Arguments: Text to be sent
#   Output: none
################################################################
send_text(){
    local TEXT=$( sed 's/^\s\+//g' <<< "${1}" )
    curl --silent "${URL}/sendMessage"                         \
            --max-time "${TIMEOUT}"                            \
            --output /dev/null                                 \
            --data-urlencode "text=${TEXT}"                    \
                --data "chat_id=${CHAT_ID}"                    \
                --data "disable_web_page_preview=${PREVIEW}"   \
                --data "parse_mode=${PARSE_MODE}"
}

################################################################
#   Description: Convert a pic or album to PDF
#   Arguments: Directory with photos
#   Output: ¿?
################################################################
topdf() {
    local dir="$1"
    convert "${dir}"/photo_* document.pdf
    # Send file
    curl --silent --form document="@${PWD}/document.pdf"             \
        "${URL}/sendDocument?chat_id=${CHAT_ID}"
    # Clean
    rm document.pdf
}

################################################################
#   Description: Offset messages
#   Arguments: none
#   Output: none
################################################################
offset(){

               curl --silent "${URL}/getUpdates"               \
                    --data "offset=$((UPDATE_ID + 1))"         \
                    --output /dev/null

}

################################################################
#   Description: Send start command message to Telegram API
#   Arguments: none
#   Output: none
################################################################
start_command(){
    PREVIEW=1
    local TEXT=$(sed 's/^ \+//' <<<"
            ℹ️ ***INFO***

            Hola! Éste bot permite generar un archivo PDF a partir de una imagen o album de imágenes. Simplemente envíame las imágenes que deseas convertir, ¡y listo!

            Nota: Cada mensaje individual genera un PDF. Como el album admite un máximo de 10 imágenes, el PDF generado no puede tener más de 10 páginas.

            💻 ***DESARROLLADOR***

            Desarrollado por @PandaFoss
            Código Fuente: https://github.com/PandaFoss/TelegramBashBots
            ")
    send_text "${TEXT}"

}
#===  END OF FUNCTIONS  ========================================

while sleep 1; do

    PARSE_MODE="markdown"
    RAW_MESSAGE=$( curl -s "${URL}/getUpdates" )
    MSG_COUNT=$( jq '.result | length' <<< "${RAW_MESSAGE}" )

    for i in $( seq 1 "${MSG_COUNT:=0}" ); do

        RESULT_COUNTER=$(( i-1 ))

        UPDATE_ID=$( jq .result[${RESULT_COUNTER}].update_id <<< "${RAW_MESSAGE}"  )
        CHAT_ID=$( jq .result[${RESULT_COUNTER}].message.chat.id <<< "${RAW_MESSAGE}"  )

        # Get data of file
        FILE_ID=$( jq  -r .result[${RESULT_COUNTER}].message.photo[3].file_id <<< "${RAW_MESSAGE}"  )
        MEDIA_GROUP_ID=$( jq -r .result[${RESULT_COUNTER}].message.media_group_id <<< "${RAW_MESSAGE}" )
        FILE_PATH=$(curl --silent "${URL}/getFile" --data "file_id=${FILE_ID}" | jq -r .result.file_path)

        #-------------------------------------------------------------------------------
        # Checking that the command was sent to your bot
        #-------------------------------------------------------------------------------
        PRIVATE=$( jq  -r .result[${RESULT_COUNTER}].message.chat.type <<< "${RAW_MESSAGE}"  | sed 's/private/true/' )
        CMD_CHECK=$( jq  -r .result[${RESULT_COUNTER}].message.text <<< "${RAW_MESSAGE}"  )
        if [[ "${CMD_CHECK}" =~ ${BOTNAME/$/\\b} ]]; then
            MESSAGE=$( sed -r "s/${BOTNAME}//" <<< "${CMD_CHECK}" )
        else
            MESSAGE="${CMD_CHECK}"
        fi

        #-------------------------------------------------------------------------------
        # If it is not a command, create a command /message with the message
        #-------------------------------------------------------------------------------
        if [[ ! "${MESSAGE}" =~ ^/[a-zA-Z0-9]+ ]]; then
            MESSAGE=$(sed --regexp-extended "s/^/\/message &/" <<< "${MESSAGE}")
        fi

        ARGS=$( awk '{$1="";print $0}' <<< "${MESSAGE}" | xargs 2>/dev/null )
        COMMAND=$( awk '{print $1}' <<< "${MESSAGE}" )
        SENDER=$( jq -r .result[${RESULT_COUNTER}].message.from.username <<< "${RAW_MESSAGE}" )

        case "${COMMAND}" in
            /start)
                start_command
                ;;
            *)
                if [[ "${FILE_ID}" == 'null' ]]; then
                    send_text "Algo salió mal... ¿Me has enviado una foto o álbum de fotos?"
                else
                    send_text "Espere un momento..."
                    # Si no es un album
                    if [[ "${MEDIA_GROUP_ID}" == 'null' ]]; then
                        TMP_DIR="$(mktemp --directory)"
                        wget "${FILE_URL}/${FILE_PATH}" -O "${TMP_DIR}/photo_$(date +%H%M%S)"
                        topdf "${TMP_DIR}"
                        rm -fr "${TMP_DIR}"
                    else # Si es un album
                        TMP_DIR="$(mktemp --directory)"
                        MGID_TEMP="${MEDIA_GROUP_ID}"
                        while true; do
                            if [[ "${MGID_TEMP}" == "${MEDIA_GROUP_ID}" ]]; then
                                wget "${FILE_URL}/${FILE_PATH}" -O "${TMP_DIR}/photo_$(date +%H%M%S)"
                                offset
                                i=$(( i+1 ))
                                RESULT_COUNTER=$(( i-1 ))
                                UPDATE_ID=$( jq .result[${RESULT_COUNTER}].update_id <<< "${RAW_MESSAGE}"  )
                                FILE_ID=$( jq  -r .result[${RESULT_COUNTER}].message.photo[3].file_id <<< "${RAW_MESSAGE}"  )
                                MEDIA_GROUP_ID=$( jq -r .result[${RESULT_COUNTER}].message.media_group_id <<< "${RAW_MESSAGE}" )
                                FILE_PATH=$(curl --silent "${URL}/getFile" --data "file_id=${FILE_ID}" | jq -r .result.file_path)
                            else
                                break
                            fi
                        done
                        topdf "${TMP_DIR}"
                        rm -fr "${TMP_DIR}"
                        break
                    fi
                fi
                ;;
        esac

        offset
    done
done
